import { apiClient } from '../lib/api/client';

import { createAuthApi } from './auth.api';
import { createUserApi } from './user.api';
import { createDoctorApi } from './doctor.api';
import { createPatientApi } from './patient.api';
import { createConsultationApi } from './consultation.api';
import { createMatchingApi } from './matching.api';
import { createChatApi } from './chat.api';
import { createSchedulingApi } from './scheduling.api';
import { createReviewApi } from './review.api';
import { createNotificationApi } from './notification.api';
import { createAdminApi } from './admin.api';
import { createNurseApi } from './nurse.api';
import { createSoapApi } from './soap.api';
import { createAiAgentsApi } from './ai-agents.api';
import { createPaymentApi } from './payment.api';

export const authApi = createAuthApi(apiClient);
export const userApi = createUserApi(apiClient);
export const doctorApi = createDoctorApi(apiClient);
export const patientApi = createPatientApi(apiClient);
export const consultationApi = createConsultationApi(apiClient);
export const matchingApi = createMatchingApi(apiClient);
export const chatApi = createChatApi(apiClient);
export const schedulingApi = createSchedulingApi(apiClient);
export const reviewApi = createReviewApi(apiClient);
export const notificationApi = createNotificationApi(apiClient);
export const adminApi = createAdminApi(apiClient);
export const nurseApi = createNurseApi(apiClient);
export const soapApi = createSoapApi(apiClient);
export const aiAgentsApi = createAiAgentsApi(apiClient);
export const paymentApi = createPaymentApi(apiClient);

export * from './auth.api';
export * from './user.api';
export * from './doctor.api';
export * from './patient.api';
export * from './consultation.api';
export * from './matching.api';
export * from './chat.api';
export * from './scheduling.api';
export * from './review.api';
export * from './notification.api';
export * from './admin.api';
export * from './nurse.api';
export * from './soap.api';
export * from './ai-agents.api';
export * from './payment.api';
